version: '2'
services:
  redis:
    image: redis
    container_name: mldm_redis
  mongo3:
    image: marsan/mongo3
    container_name: mldm_mongo3
  pg:
    image: postgres
    container_name: mldm_pg
  env:
    build: .
    command: ipynb #bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ~/workspace:/home/workspace
    depends_on:
      - mongo3
      - redis
      - pg
    ports:
      - "8880-8900:8880-8900"
    container_name: mldm_env
    devices:
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidia1:/dev/nvidia1
      - /dev/nvidia2:/dev/nvidia2
      - /dev/nvidia3:/dev/nvidia3
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-uvm:/dev/nvidia-uvm

